# Configure.
environment:
  PATH: C:\%PYTHON%;C:\%PYTHON%\Scripts;%PATH%
  PYTHON: Python35
  matrix:
    - TOX_ENV: py37
    - TOX_ENV: py36
    - TOX_ENV: py35
    - TOX_ENV: py27
    - TOX_ENV: py
      PYTHON: Python37-x64
    - TOX_ENV: py
      PYTHON: Python36-x64
    - TOX_ENV: py
      PYTHON: Python35-x64
    - TOX_ENV: py
      PYTHON: Python27-x64

# Run.
install:
  - python -m pip install -U pip tox
  - git config --global user.email "builds@appveyor.com"
  - git config --global user.name "AppVeyor"
build_script: pip install tox
test_script: tox -e %TOX_ENV%
on_success: IF %TOX_ENV% NEQ lint pip install codecov & codecov
